// Auto-generated by convert.ts — do not edit by hand.
// Place this in your VitePress config's sidebar field, e.g.:
//
//   import sidebar from './sidebar'
//   export default defineConfig({ themeConfig: { sidebar } })

export default [
  {
    "text": "Area 1",
    "collapsed": true,
    "items": [
      {
        "text": "document1",
        "link": "/Area 1/document1"
      },
      {
        "text": "document2",
        "link": "/Area 1/document2"
      }
    ]
  },
  {
    "text": "Area 2",
    "collapsed": true,
    "items": [
      {
        "text": "document3",
        "link": "/Area 2/document3"
      }
    ]
  }
] as const;
